
services:
  songmanager:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./Songs:/app/songs:rw,Z